name: Compilar para Xbox 360

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Baixar o codigo do repositorio
      uses: actions/checkout@v4

    - name: Compilar usando o Makefile
      run: |
        make

    - name: Disponibilizar para Download
      uses: actions/upload-artifact@v4
      with:
        name: Executavel-Xbox360
        path: programa_controle
